#!/bin/bash
set -eu

DOCKER_IMAGE_NAME=document-download-api
PORT=7000

AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-"$(aws configure get aws_access_key_id)"}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-"$(aws configure get aws_secret_access_key)"}

FRONTEND_HOSTNAME=${FRONTEND_HOSTNAME:-"http://host.docker.internal:7001"}
# The scheme of DOCUMENT_DOWNLOAD_API_HOSTNAME gets added in code
DOCUMENT_DOWNLOAD_API_HOSTNAME=${DOCUMENT_DOWNLOAD_API_HOSTNAME:-"host.docker.internal:7000"}
ANTIVIRUS_API_HOST=${ANTIVIRUS_API_HOST:-"http://host.docker.internal:6016"}

docker run -it --rm \
  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  -e NOTIFY_ENVIRONMENT=$NOTIFY_ENVIRONMENT \
  -e FLASK_APP=$FLASK_APP \
  -e FLASK_DEBUG=$FLASK_DEBUG \
  -e FRONTEND_HOSTNAME=$FRONTEND_HOSTNAME \
  -e DOCUMENT_DOWNLOAD_API_HOSTNAME=$DOCUMENT_DOWNLOAD_API_HOSTNAME \
  -e ANTIVIRUS_API_HOST=$ANTIVIRUS_API_HOST \
  -e ANTIVIRUS_ENABLED=${ANTIVIRUS_ENABLED:-0} \
  -e WERKZEUG_DEBUG_PIN=${WERKZEUG_DEBUG_PIN:-"off"} \
  -e PORT=${PORT} \
  -p 127.0.0.1:${PORT}:${PORT} \
  -v $(pwd):/home/vcap/app \
  ${DOCKER_IMAGE_NAME} \
  ${@}
